{{- if .Values.auth.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "55ndeep.fullname" . }}-auth
  labels:
    {{- include "55ndeep.labels" . | nindent 4 }}
type: Opaque
data:
  HEALTH_API_KEY: {{ .Values.auth.apiKey | b64enc | quote }}
{{- end }}
