apiVersion: v1
kind: Secret
metadata:
  name: {{ include "55ndeep.fullname" . }}-secret
  labels:
    {{- include "55ndeep.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.apiKey }}
  HEALTH_API_KEY: {{ .Values.auth.apiKey | quote }}
  {{- end }}
  {{- if .Values.model.openai.apiKey }}
  OPENAI_API_KEY: {{ .Values.model.openai.apiKey | quote }}
  {{- end }}
  {{- if .Values.model.anthropic.apiKey }}
  ANTHROPIC_API_KEY: {{ .Values.model.anthropic.apiKey | quote }}
  {{- end }}
